### ISSUE TITLE
Add ANSI color codes

### ISSUE THREAD

**Issue by firlus** [snugfox/ansi-escapes#1]
Hey there,
thanks for your library, you helped me a lot for a personal project!
I feel like you also could include color codes in the library and I'd be more than happy to implement that!
Let me know If I can open a pull request!

Cheers,
Michael

**Comment by snugfox** [comment]
Hi Michael,

I am glad to hear that you found my library useful. You are certainly welcome to open a pull request for color codes support.

**Comment by firlus** [comment]
Thanks!
